### ISSUE TITLE
`RedundantIndexChecker` couldn't be disabled via `.database_consistency.yml`

### ISSUE THREAD

**Issue by ojab** [djezzzl/database_consistency#108]
Test repo https://github.com/ojab/tst

There are two indices on `Company#external_id` and `.database_consistency.yml` with
```yaml
Company:
  RedundantIndexChecker:
    enabled: false
  external_id:
    RedundantIndexChecker:
      enabled: false
```
but `bundle exec database_consistency` still complains.

**Comment by djezzzl** [comment]
Hi @ojab,

Thank you for reaching out here!

Based on your test example, you receive:
```
bundle exec database_consistency
RedundantIndexChecker fail Company bar index is redundant as (foo) covers it
RedundantIndexChecker fail Company foo index is redundant as (bar) covers it
```

In order to disable those, your config file should look like:
```
Company:
  foo:
    RedundantIndexChecker:
      enabled: false
  bar:
    RedundantIndexChecker:
      enabled: false
```

With this config, it stops failing properly.

**Comment by djezzzl** [comment]
I apologize that it doesn't visible that it should be disabled in that way. I think one day we will have a better explanatory output. Feel free to contribute if you want :+1:

**Comment by djezzzl** [comment]
I'm closing the issue for now but it it still fails for you, feel free to reopen it.

**Comment by ojab** [comment]
oh, so it's index name and not column names! [Example config](https://github.com/djezzzl/database_consistency/blob/master/rails-example/.database_consistency.yml) says
```yaml
  name+email:
    MissingUniqueIndexChecker:
      enabled: true
```
so I guessed it should be column names.
