### ISSUE TITLE
global ignore not working

### ISSUE THREAD

**Issue by grosser** [djezzzl/database_consistency#123]
I followed the rails install and got it running ... there is too much, so I need to ignore 90%
so I added to `.database_consistency.yml`
```
RedundantIndexChecker:
  enabled: false
```

... but `bundle exec database_consistency` still shows:
```
RedundantIndexChecker fail ProductProject index_product_projects_on_project_id index is redundant as (index_product_projects_on_project_id_and_product_id) covers it
```

(individual ignores work though)

**Comment by djezzzl** [comment]
Hi @grosser, 

Thank you for reaching out! I think that you should add this key under `DatabaseConsistencyChecker:`, something like:

```
DatabaseConsistencyCheckers:
  MissingIndexChecker:
    enabled: true # 1st priority (completely turn off particular checker)
  MissingUniqueIndexChecker:
    enabled: true
  ColumnPresenceChecker:
    enabled: true
  NullConstraintChecker:
    enabled: true
```

I'll close the issue but feel free to reopen it in case it didn't work for you. 

P.S. Any suggestion how we can improve the documention is very welcome!
