### ISSUE TITLE
Add ability to ignore certain namespaces

### ISSUE THREAD

**Issue by mak-dunkelziffer** [djezzzl/database_consistency#173]
There are cases, where it would be nice to have a more comfortable method of ignoring multiple models or attributes at once in the config.

I have one case where the namespace `DataMigration` contains models that are not used in production and are kept for historic reasons. So I currently have 44 lines of the following in my config:
```yaml
DataMigration::Article
  enabled: false
...
DataMigration::User
  enabled: false
```

I have another case where errors are "inherited" from another gem and I have 13 lines of the following in my config:
```yaml
User:
  thredded_private_posts:
    enabled: false
...
  thredded_post_moderated_records:
    enabled: false
```
Being able to ignore all attributes starting with `thredded_` (per model or even globally) would be nice.
