### ISSUE TITLE
Improve Documentation to describe how to work with indexes

### ISSUE THREAD

**Issue by yashka713** [djezzzl/database_consistency#219]
For example, I have a User model with `Devise` inside. `Devise` generates a batch of columns and indexes for them:

Columns:
- `less_password_token`
- `reset_password_token`
- `invitation_token`

And indexes:
- `index_users_on_less_password_token`
- `index_users_on_reset_password_token`
- `index_users_on_invitation_token`

Currently, [documentation](https://github.com/djezzzl/database_consistency/wiki/configuration) does not clearly describe how to work with indexes. So could you copy this to the database configuration example?

```yml
User:
  index_users_on_less_password_token:
    UniqueIndexChecker:
      enabled: false
  index_users_on_reset_password_token:
    UniqueIndexChecker:
      enabled: false
  index_users_on_invitation_token:
    UniqueIndexChecker:
      enabled: false
```
