### ISSUE TITLE
How to run only specific checkers?

### ISSUE THREAD

**Issue by paul** [djezzzl/database_consistency#226]
Given the example, I'd have expected this to work:

```yaml
  All:
    enabled: false
  ForeignKeyChecker:
    enabled: true
  ForeignKeyTypeChecker:
    enabled: true
  ForeignKeyCascadeChecker:
    enabled: true
```

But when I run it, I get no output:

```
$ bundle exec database_consistency
Loaded configurations: .database_consistency.yml

$
```

When I set `All: enabled: true`, I get fails for those checkers (and all the others, which I don't want to worry about right now).

```
$ be database_consistency | grep ForeignKey
ForeignKeyChecker ok Account owner
ForeignKeyTypeChecker ok Account owner
ForeignKeyTypeChecker ok Account exports
ForeignKeyChecker fail Account embedded_analyst should have foreign key in the database
ForeignKeyTypeChecker ok Account embedded_analyst
ForeignKeyTypeChecker ok Account account_invitations
...
```

I can workaround by generating a todo file and deleting the ForeignKey entries, but this seems like it may be a bug?

Also is there a way to only print the failures? The wiki implies that `log_level: DEBUG` will cause it to print the successes, but with that omitted I still get them, and `log_level: INFO` and ERROR still print them as well.
