### ISSUE TITLE
Possible to run as GitHub Action?

### ISSUE THREAD

**Issue by vfonic** [djezzzl/database_consistency#246]
I tried to add `bundle exec database_consistency` as part of my build/CI setup to GitHub Action, but it fails and I cannot figure out how to fix it. `bundle exec database_consistency` passes locally.

Here's all the relevant output that I get inside of the GitHub Action. I don't know how to access the log txt file.

![Screenshot 2025-01-05 at 19 21 02](https://github.com/user-attachments/assets/438ff757-94ce-4740-94c0-52519c5d247b)

**Comment by vfonic** [comment]
Figured it out. To get the logs, I needed to store them as artifact that can be downloaded:

```yaml
      # Upload database_consistency logs
      - id: getfilename
        if: failure()
        run: echo "::set-output name=file::$(ls database_consistency_*.txt)"
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          path: ${{ steps.getfilename.outputs.file }}
```

When I downloaded the failure log, I found out what the error was:

```
<===begin===>
Metadata:
model: Xxx
checker: DatabaseConsistency::Checkers::MissingTableChecker
Stack trace:
/home/runner/work/xxx/xxx/vendor/bundle/ruby/3.4.0/gems/activerecord-8.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:69:in 'ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.new_client': connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory (ActiveRecord::ConnectionNotEstablished)
	Is the server running locally and accepting connections on that socket?
```


I made sure that I prepare and start the database before running `bundle exec database_consistency` and then it worked.

To make sure that the db is prepared and started, you need to do something along the lines of:

```yaml
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.40

      - name: Prepare database
        run: bin/rails db:test:prepare

      - name: Check database consistency
        run: bundle exec database_consistency
```
